# -*- coding: utf-8 -*-
"""Ancient_Script_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgeVWvilqBV_lNeg0RaKLyOHMoMW52QK
"""

import zipfile, os

zip_path = "dataset.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted folders:", os.listdir(extract_path))

extract_path = "/content/dataset/manuscript"

import os

print("Sanskrit images:", len(os.listdir("/content/dataset/manuscript/sanskrit")))
print("Tamil images:", len(os.listdir("/content/dataset/manuscript/tamil")))

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping

DATASET_PATH = "/content/dataset/manuscript"
CATEGORIES = ["sanskrit", "tamil"]
IMG_SIZE = 64

data = []
labels = []

for label, category in enumerate(CATEGORIES):
    folder_path = os.path.join(DATASET_PATH, category)

    for img_name in os.listdir(folder_path):
        img_path = os.path.join(folder_path, img_name)
        try:
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0
            data.append(img)
            labels.append(label)
        except:
            print("Skipped:", img_path)

X = np.array(data).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
y = np.array(labels)

print("Total images loaded:", len(X))

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

datagen = ImageDataGenerator(
    rotation_range=5,
    width_shift_range=0.05,
    height_shift_range=0.05,
    zoom_range=0.1
)

datagen.fit(X_train)

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(64,64,1)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    datagen.flow(X_train, y_train, batch_size=16),
    validation_data=(X_test, y_test),
    epochs=15,
    callbacks=[early_stop]
)

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Final Test Accuracy:", round(test_acc * 100, 2), "%")

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.legend()
plt.title("Model Accuracy")

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.legend()
plt.title("Model Loss")

plt.show()

import os

print(os.listdir("/content/dataset/manuscript/sanskrit"))

import cv2
import matplotlib.pyplot as plt

# ---- Correct single-character image paths ----
sanskrit_path = "/content/dataset/manuscript/sanskrit/book1_page-0001_word_12.png"
tamil_path    = "/content/dataset/manuscript/tamil/tamil1_page-0001_word_33.png"

def load_and_prepare(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise ValueError(f"Image not found: {path}")
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img_norm = img / 255.0
    return img, img_norm

def recognize(img_norm):
    img_norm = img_norm.reshape(1, IMG_SIZE, IMG_SIZE, 1)
    pred = model.predict(img_norm, verbose=0)[0][0]
    return "Sanskrit" if pred < 0.5 else "Tamil"

san_img, san_norm = load_and_prepare(sanskrit_path)
tam_img, tam_norm = load_and_prepare(tamil_path)

# ---- Recognition ----
san_label = recognize(san_norm)
tam_label = recognize(tam_norm)

# ---- Reconstruction ----
san_recon = reconstruct_image(san_norm)
tam_recon = reconstruct_image(tam_norm)

# ---- Display layout ----
plt.figure(figsize=(8,8))

plt.subplot(2,2,1)
plt.imshow(san_img, cmap='gray')
plt.title(f"Sanskrit Original\nRecognized: {san_label}")
plt.axis('off')

plt.subplot(2,2,2)
plt.imshow(san_recon, cmap='gray')
plt.title("Sanskrit Reconstructed")
plt.axis('off')

plt.subplot(2,2,3)
plt.imshow(tam_img, cmap='gray')
plt.title(f"Tamil Original\nRecognized: {tam_label}")
plt.axis('off')

plt.subplot(2,2,4)
plt.imshow(tam_recon, cmap='gray')
plt.title("Tamil Reconstructed")
plt.axis('off')

plt.tight_layout()
plt.show()

from sklearn.metrics import mean_squared_error

# ---- Sanskrit MSE ----
mse_sanskrit = mean_squared_error(
    san_img.flatten(),
    san_recon.flatten()
)
# ---- Tamil MSE ----
mse_tamil = mean_squared_error(
    tam_img.flatten(),
    tam_recon.flatten()
)

print("Reconstruction MSE (Sanskrit):", mse_sanskrit)
print("Reconstruction MSE (Tamil):", mse_tamil)